# Pandas Series01

So, first in order to use the Series defined in the pandas library we need to import it to our notebook.
the first line of code imports pandas and numpy to this notebook.

In [1]:
import pandas as pd
import numpy as np

## Series using NumPy-array:

In [5]:
array = np.array([1,2,3,4,5,'string',[0,1,0,2]])

0               1
1               2
2               3
3               4
4               5
5          string
6    [0, 1, 0, 2]
dtype: object

This is how we can define an NumPy array.
Basically, we can give any list type object to the argument of 'np.array()' method and it will generate a NumPy array.
NumPy arrays are very useful in storing the outputs generated by scientific computations. and pandas can help us manipulating the data stored inside these array objects.

In [3]:
series1 = pd.Series(array)

Here 'series1' is an object of type pandas-series.
To create a pandas series from an numpy array we can use the array name as the argument to the 'pd.Series()' method.
This line of code will create a series binded with name 'series1' and will assign the data found inside the array to series1.
So, how about printing this series!??

In [6]:
series1

0               1
1               2
2               3
3               4
4               5
5          string
6    [0, 1, 0, 2]
dtype: object

The name of the series (here, 'series1') works as a keyword and prints that series.
As we can see from the output of the line-6, Pandas series index starts from 0.

## Using Lists

We can also create series from python list objects in a very similar manner how we created series using array objects from numpy

In [9]:
list1 = [1,2,3,4,5,'python',np.nan,'data-science']

In order to create a series using python lists consider the list 'list1'.

In [10]:
series2 = pd.Series(list1)

As, we did in the case of numpy array. Here, also we just argument the 'pd.Series()' method with the list name here 'list1'.

So, let's try to print this series

In [11]:
series2

0               1
1               2
2               3
3               4
4               5
5          python
6             NaN
7    data-science
dtype: object

As you might have expected it just created a series representing the data stored inside the 'list1'

## Using Dictionary

In [ ]:
We can also create pandas series using python dictionaries. Consider the dict1 in the following line

In [15]:
dict1 = {
    '@': 'Symbol',
    '2': 12,
    22 : 'twenty-two'
}

In [16]:
series3 = pd.Series(dict1)

This will create a series using the argumented dictionary name.

Let's create another series using this exact same python dictionary but using a little different syntax.

In [17]:
series4 = pd.Series({
  '@' : 'Symbol',
  '2' : 12,
   22 : "twenty-two" 
})

Let's try to print the contents of 'series3' and 'series4' one by one.

In [18]:
series3

@         Symbol
2             12
22    twenty-two
dtype: object

In [19]:
series4

@         Symbol
2             12
22    twenty-two
dtype: object

See, the outputs of line 18 and line 19 closely, they are indentical.

# Exercise Time:

1. Create a pandas series containing integers (100,1001,10001), a string 'This is a string', and a not a number   type object usign numpy-array. and name that series 's1'.
Enter you solution in line-20.

In [20]:
# Solution for exercise1

2. Create a pandas series containing the exact same data as in exercise 1. but use a python list this time.
Enter your solution in line 22

In [23]:
# Solution for exercise2

3. Create a pandas series containing the exact same data as in exercise 1. but use a python dictionary this time.
Enter your solution in line 24

In [24]:
# Solution for exercise3